eezs <- c("High seas",
          "Spain",
          "Tunisia",
          "Italy",
          "Libya",
          "Turkey",
          "Algeria",
          "Malta",
          "Greece",
          "United States",
          "Japan",
          "United Kingdom",
          "New Zealand",
          "France",
          "Australia",
          "Georgia",
          "Brazil",
          "Portugal",
          "Republic of Mauritius",
          "China",
          "Russia",
          "Spain",
          "Morocco",
          "Argentina",
          "Madagascar",
          "Ukraine",
          "Bahamas",
          "Mexico",
          "Uruguay",
          "Bulgaria",
          "South Africa",
          "Canada",
          "Egypt",
          "Morocco",
          "Croatia",
          "Romania",
          "Chile",
          "Japan",
          "Russia",
          "Monaco",
          "Seychelles",
          "Ireland",
          "South Korea",
          "Ecuador",
          "Colombia",
          "France",
          "Madagascar",
          "Mauritius",
          "Cape Verde",
          "Albania",
          "Dominican Republic",
          "Indonesia",
          "India",
          "Montenegro",
          "Cyprus",
          "Norway",
          "Micronesia",
          "Malaysia",
          "Namibia",
          "Denmark",
          "Peru",
          "Western Sahara",
          "North Korea",
          "Mozambique",
          "Maldives",
          "Haiti",
          "Philippines",
          "Panama",
          "Vanuatu",
          "Palau", "Sri Lanka", "Costa Rica", "Syria", "Jamaica", "France","Vanuatu", "Netherlands", 
          "Iceland", "Vietnam", "Angola", "Federal Republic of Somalia", "Brunei", "Taiwan", "Cuba",
          "Comores", "Singapore", "Tanzania", "Pakistan", "Germany", "Taiwan","Japan","China", "Mauritius", 
          "Papua New Guinea", "Lebanon", "Japan","South Korea", "Madagascar","France", "Guinea-Bissau", 
          "Haiti","United States","Jamaica", "Tonga","France","Comores", "Oman", "Fiji", "Israel", "Palestine", 
          "Kenya", "Senegal", "Yemen", "Gabon", "Saudi Arabia", "Myanmar", "Republic of the Congo", 
          "Democratic Republic of the Congo", "Venezuela", "Antarctica", "Guinea", "Mauritania", "Sudan", 
          "Colombia","Dominican Republic","Venezuela", "Solomon Islands", "Antigua and Barbuda", 
          "Kenya","Federal Republic of Somalia", "United States","Dominican Republic", "Honduras", 
          "Venezuela","Netherlands","Dominican Republic", "Djibouti", "Bangladesh", "Marshall Islands", "Gambia", 
          "Equatorial Guinea", "Sierra Leone", "Ghana", "Nicaragua", "Eritrea", "Sudan","Egypt", "Ivory Coast", 
          "Thailand", "Eritrea","Djibouti", "Iran", "Kiribati", "Liberia", "Barbados", "Guyana", "Suriname", 
          "Sweden", "Guatemala", "Trinidad and Tobago", "Guyana","Trinidad and Tobago","Venezuela", "Belize", 
          "Dominica", "Sao Tome and Principe", "Nauru", "Tuvalu", "East Timor", "El Salvador", 
          "Saint Kitts and Nevis", "Saint Vincent and the Grenadines", "Saint Lucia", "Samoa", "Benin", 
          "Grenada", "Togo", "Finland", "Poland", "Cambodia", "Nigeria", "Estonia")
length(unique(eezs))
unique(eezs)

(1/143)*100

(0.75/142)*100

